apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    service: {{ .Release.Name }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /test-{{ .Chart.Name }}
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 8890
