apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    service: {{ .Release.Name }}
spec:
  ports:
    - port: 8890
      targetPort: 8890
  selector:
    service: {{ .Release.Name }}
    app: service
