apiVersion: v1
kind: Pod
metadata:
  labels:
    app: benchmark
    service: bank
  name: service-benchmark
  namespace: default
spec:
      containers:
          - name: bank-bench
            image: bank-bench
            imagePullPolicy: Never
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
